# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './GrowPiAppUi.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        font = QtGui.QFont()
        font.setPointSize(18)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 801, 481))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.l_main = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.l_main.setContentsMargins(0, 0, 0, 0)
        self.l_main.setObjectName("l_main")
        self.tw_main = QtWidgets.QTabWidget(self.horizontalLayoutWidget)
        self.tw_main.setTabPosition(QtWidgets.QTabWidget.South)
        self.tw_main.setIconSize(QtCore.QSize(20, 20))
        self.tw_main.setObjectName("tw_main")
        self.tab_temp = QtWidgets.QWidget()
        self.tab_temp.setObjectName("tab_temp")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_temp)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 801, 451))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.l_temp = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.l_temp.setContentsMargins(0, 0, 0, 0)
        self.l_temp.setObjectName("l_temp")
        self.tw_temp = QtWidgets.QTabWidget(self.horizontalLayoutWidget_2)
        self.tw_temp.setTabPosition(QtWidgets.QTabWidget.East)
        self.tw_temp.setIconSize(QtCore.QSize(20, 20))
        self.tw_temp.setObjectName("tw_temp")
        self.tab_temp_data = QtWidgets.QWidget()
        self.tab_temp_data.setObjectName("tab_temp_data")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab_temp_data)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(-1, -1, 771, 441))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.plotWidget = GraphicsLayoutWidget(self.horizontalLayoutWidget_4)
        self.plotWidget.setObjectName("plotWidget")
        self.horizontalLayout_4.addWidget(self.plotWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/IconGraph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tw_temp.addTab(self.tab_temp_data, icon, "")
        self.tab_temp_settings = QtWidgets.QWidget()
        self.tab_temp_settings.setObjectName("tab_temp_settings")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_temp_settings)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 761, 441))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_cur = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lbl_cur.setFont(font)
        self.lbl_cur.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_cur.setObjectName("lbl_cur")
        self.gridLayout.addWidget(self.lbl_cur, 1, 0, 1, 1)
        self.lcd_cur_start = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcd_cur_start.setDigitCount(2)
        self.lcd_cur_start.setObjectName("lcd_cur_start")
        self.gridLayout.addWidget(self.lcd_cur_start, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 1)
        self.lbl_new = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lbl_new.setFont(font)
        self.lbl_new.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_new.setObjectName("lbl_new")
        self.gridLayout.addWidget(self.lbl_new, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.lcd_cur_stop = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcd_cur_stop.setDigitCount(2)
        self.lcd_cur_stop.setObjectName("lcd_cur_stop")
        self.gridLayout.addWidget(self.lcd_cur_stop, 4, 0, 1, 1)
        self.lcd_set_stop = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcd_set_stop.setDigitCount(2)
        self.lcd_set_stop.setObjectName("lcd_set_stop")
        self.gridLayout.addWidget(self.lcd_set_stop, 4, 1, 1, 1)
        self.lcd_set_start = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcd_set_start.setDigitCount(2)
        self.lcd_set_start.setObjectName("lcd_set_start")
        self.gridLayout.addWidget(self.lcd_set_start, 2, 1, 1, 1)
        self.dial_stop = QtWidgets.QDial(self.gridLayoutWidget)
        self.dial_stop.setMaximum(50)
        self.dial_stop.setSingleStep(1)
        self.dial_stop.setObjectName("dial_stop")
        self.gridLayout.addWidget(self.dial_stop, 4, 2, 1, 1)
        self.dial_start = QtWidgets.QDial(self.gridLayoutWidget)
        self.dial_start.setMaximum(50)
        self.dial_start.setObjectName("dial_start")
        self.gridLayout.addWidget(self.dial_start, 2, 2, 1, 1)
        self.pb_set_temp = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.pb_set_temp.setFont(font)
        self.pb_set_temp.setObjectName("pb_set_temp")
        self.gridLayout.addWidget(self.pb_set_temp, 2, 3, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/IconCog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tw_temp.addTab(self.tab_temp_settings, icon1, "")
        self.l_temp.addWidget(self.tw_temp)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/IconThermometer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tw_main.addTab(self.tab_temp, icon2, "")
        self.tab_light = QtWidgets.QWidget()
        self.tab_light.setObjectName("tab_light")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab_light)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(-1, -1, 801, 451))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.l_light = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.l_light.setContentsMargins(0, 0, 0, 0)
        self.l_light.setObjectName("l_light")
        self.tw_light = QtWidgets.QTabWidget(self.horizontalLayoutWidget_5)
        self.tw_light.setTabPosition(QtWidgets.QTabWidget.East)
        self.tw_light.setIconSize(QtCore.QSize(20, 20))
        self.tw_light.setObjectName("tw_light")
        self.tab_light_data = QtWidgets.QWidget()
        self.tab_light_data.setObjectName("tab_light_data")
        self.tw_light.addTab(self.tab_light_data, icon, "")
        self.tab_light_settings = QtWidgets.QWidget()
        self.tab_light_settings.setObjectName("tab_light_settings")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_light_settings)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(-1, -1, 761, 441))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_on = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lbl_on.setFont(font)
        self.lbl_on.setObjectName("lbl_on")
        self.gridLayout_3.addWidget(self.lbl_on, 1, 1, 1, 1)
        self.lcd_cur_on_h = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.lcd_cur_on_h.setDigitCount(2)
        self.lcd_cur_on_h.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcd_cur_on_h.setObjectName("lcd_cur_on_h")
        self.gridLayout_3.addWidget(self.lcd_cur_on_h, 1, 2, 1, 1)
        self.lcd_new_off_h = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.lcd_new_off_h.setDigitCount(2)
        self.lcd_new_off_h.setObjectName("lcd_new_off_h")
        self.gridLayout_3.addWidget(self.lcd_new_off_h, 3, 5, 1, 1)
        self.lbl_off = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lbl_off.setFont(font)
        self.lbl_off.setObjectName("lbl_off")
        self.gridLayout_3.addWidget(self.lbl_off, 3, 1, 1, 1)
        self.pb_set_light = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.pb_set_light.setFont(font)
        self.pb_set_light.setObjectName("pb_set_light")
        self.gridLayout_3.addWidget(self.pb_set_light, 1, 9, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 4, 1, 1)
        self.lbl_on_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lbl_on_2.setFont(font)
        self.lbl_on_2.setObjectName("lbl_on_2")
        self.gridLayout_3.addWidget(self.lbl_on_2, 0, 6, 1, 1)
        self.lbl_on_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lbl_on_3.setFont(font)
        self.lbl_on_3.setObjectName("lbl_on_3")
        self.gridLayout_3.addWidget(self.lbl_on_3, 0, 8, 1, 1)
        self.dial_on_m = QtWidgets.QDial(self.gridLayoutWidget_3)
        self.dial_on_m.setMaximum(59)
        self.dial_on_m.setObjectName("dial_on_m")
        self.gridLayout_3.addWidget(self.dial_on_m, 1, 8, 1, 1)
        self.lcd_new_on_h = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.lcd_new_on_h.setDigitCount(2)
        self.lcd_new_on_h.setObjectName("lcd_new_on_h")
        self.gridLayout_3.addWidget(self.lcd_new_on_h, 1, 5, 1, 1)
        self.lcd_cur_on_m = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.lcd_cur_on_m.setDigitCount(2)
        self.lcd_cur_on_m.setObjectName("lcd_cur_on_m")
        self.gridLayout_3.addWidget(self.lcd_cur_on_m, 1, 3, 1, 1)
        self.lcd_new_on_m = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.lcd_new_on_m.setDigitCount(2)
        self.lcd_new_on_m.setObjectName("lcd_new_on_m")
        self.gridLayout_3.addWidget(self.lcd_new_on_m, 1, 7, 1, 1)
        self.dial_off_h = QtWidgets.QDial(self.gridLayoutWidget_3)
        self.dial_off_h.setMaximum(23)
        self.dial_off_h.setObjectName("dial_off_h")
        self.gridLayout_3.addWidget(self.dial_off_h, 3, 6, 1, 1)
        self.dial_off_m = QtWidgets.QDial(self.gridLayoutWidget_3)
        self.dial_off_m.setMaximum(59)
        self.dial_off_m.setObjectName("dial_off_m")
        self.gridLayout_3.addWidget(self.dial_off_m, 3, 8, 1, 1)
        self.lcd_new_off_m = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.lcd_new_off_m.setDigitCount(2)
        self.lcd_new_off_m.setObjectName("lcd_new_off_m")
        self.gridLayout_3.addWidget(self.lcd_new_off_m, 3, 7, 1, 1)
        self.dial_on_h = QtWidgets.QDial(self.gridLayoutWidget_3)
        self.dial_on_h.setMaximum(23)
        self.dial_on_h.setObjectName("dial_on_h")
        self.gridLayout_3.addWidget(self.dial_on_h, 1, 6, 1, 1)
        self.lcd_cur_off_m = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.lcd_cur_off_m.setDigitCount(2)
        self.lcd_cur_off_m.setObjectName("lcd_cur_off_m")
        self.gridLayout_3.addWidget(self.lcd_cur_off_m, 3, 3, 1, 1)
        self.lcd_cur_off_h = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.lcd_cur_off_h.setDigitCount(2)
        self.lcd_cur_off_h.setObjectName("lcd_cur_off_h")
        self.gridLayout_3.addWidget(self.lcd_cur_off_h, 3, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 4, 6, 1, 1)
        self.tw_light.addTab(self.tab_light_settings, icon1, "")
        self.l_light.addWidget(self.tw_light)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/IconLight.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tw_main.addTab(self.tab_light, icon3, "")
        self.tab_exit = QtWidgets.QWidget()
        self.tab_exit.setObjectName("tab_exit")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_exit)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 801, 451))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.l_exit = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.l_exit.setContentsMargins(0, 0, 0, 0)
        self.l_exit.setObjectName("l_exit")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.l_exit.addItem(spacerItem4)
        self.pbExit = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pbExit.setObjectName("pbExit")
        self.l_exit.addWidget(self.pbExit)
        self.pbReboot = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pbReboot.setObjectName("pbReboot")
        self.l_exit.addWidget(self.pbReboot)
        self.pbShutdown = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pbShutdown.setObjectName("pbShutdown")
        self.l_exit.addWidget(self.pbShutdown)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.l_exit.addItem(spacerItem5)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/IconShutdown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tw_main.addTab(self.tab_exit, icon4, "")
        self.l_main.addWidget(self.tw_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tw_main.setCurrentIndex(1)
        self.tw_temp.setCurrentIndex(1)
        self.tw_light.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tw_temp.setTabText(self.tw_temp.indexOf(self.tab_temp_data), _translate("MainWindow", "Data"))
        self.lbl_cur.setText(_translate("MainWindow", "Current"))
        self.lbl_new.setText(_translate("MainWindow", "New"))
        self.pb_set_temp.setText(_translate("MainWindow", "SET"))
        self.tw_temp.setTabText(self.tw_temp.indexOf(self.tab_temp_settings), _translate("MainWindow", "Settings"))
        self.tw_main.setTabText(self.tw_main.indexOf(self.tab_temp), _translate("MainWindow", "Temperature"))
        self.tw_light.setTabText(self.tw_light.indexOf(self.tab_light_data), _translate("MainWindow", "Data"))
        self.lbl_on.setText(_translate("MainWindow", "AAN"))
        self.lbl_off.setText(_translate("MainWindow", "UIT"))
        self.pb_set_light.setText(_translate("MainWindow", "SET"))
        self.lbl_on_2.setText(_translate("MainWindow", "UUR"))
        self.lbl_on_3.setText(_translate("MainWindow", "MIN"))
        self.tw_light.setTabText(self.tw_light.indexOf(self.tab_light_settings), _translate("MainWindow", "Settings"))
        self.tw_main.setTabText(self.tw_main.indexOf(self.tab_light), _translate("MainWindow", "Light"))
        self.pbExit.setText(_translate("MainWindow", "Exit"))
        self.pbReboot.setText(_translate("MainWindow", "Reboot"))
        self.pbShutdown.setText(_translate("MainWindow", "Shutdown"))
        self.tw_main.setTabText(self.tw_main.indexOf(self.tab_exit), _translate("MainWindow", "Exit"))


from pyqtgraph import GraphicsLayoutWidget
